### ISSUE TITLE
通过goproxy访问google偶尔会被认为是机器人

### ISSUE THREAD

**Issue by catinred2** [shell909090/goproxy#10]
页面报如下错误

```
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
```

**Comment by shell909090** [comment]
这和goproxy没啥关系，主要是你用的vps机房里经常有爬虫去爬google的服务器，导致google评估你的机房IP段很可能是机器人的段。加上你自己的一些行为，就。。。那啥了。。。
你想，goproxy可是tcp级代理啊。唯一可能造成影响的，就是http请求代理部分用了golang内置的代码（出自于google手笔）。。。要是google自己当自己是机器人。。。好吧。。。其实他也没说错。。。

**Comment by catinred2** [comment]
之前一直用ss，没出现这个情况。近期换goproxy就出现了。不过也可能是碰巧，机房里面有其他人做坏事。

**Comment by shell909090** [comment]
另一方面说，goproxy是个完整的tcp层的东西，几乎没办法看出是不是机器人。真正有影响的是代理系统的行为。而这个代理系统是抄的golang自带的东西。所以如果是这样，我也很难想到理由。例如是哪个具体的header行为不正确，导致你被判定为了机器人。

**Comment by catinred2** [comment]
只能怀疑google有什么黑科技了

**Comment by icexin** [comment]
@shell909090 我也遇到这个问题，之前用ss的时候没有这个问题，我怀疑是http头造成的。

**Comment by shell909090** [comment]
也只可能是头部了。
不过我记得我的头部是照抄的golang自己的代码。。。

**Comment by catinred2** [comment]
FYI [Google屏蔽Linode的IPv6导致SSH隧道不可用](http://codelife.me/blog/2013/11/16/google-block-linode-traffic-over-ipv6/)

**Comment by shell909090** [comment]
有道理。我向上回源的时候确实没考虑是不是从tcp6出去的。
改一改。

**Comment by qyin** [comment]
遇到同样的问题，同样一台VPS。通过SS代理就没有问题，但是通过goproxy就有这个问题，很奇怪。

**Comment by qyin** [comment]
经排查发现我VPS的 ipv6 ip被 Google Ban 掉了。是否有办法在不修改 vps 配置的情况下，让 goproxy 默认通过 ipv4 连出去？

**Comment by kongfei605** [comment]
goproxy的配置文件server.json中"listen": ":5233", 替换为 "listen": "0.0.0.0:5233"
 试试，这样能限定只使用ipv4。

2016-07-10 10:54 GMT+08:00 Qiang Yin <notifications@github.com>:

**Comment by kongfei605** [comment]
现在怎么样？@qyin

**Comment by qyin** [comment]
@kongfei605 抱歉，因为之后没有做过测试。所以现在还不知道这个方案是否行的通。

**Comment by shell909090** [comment]
现在配置里面带有forceipv4，可以限制不从ipv6出去。
