### ISSUE TITLE
程序无法编译

### ISSUE THREAD

**Issue by yuan78** [shell909090/goproxy#11]
程序无法编译：

C:\Users\XXX>go get github.com/shell909090/goproxy
package github.com/shell909090/goproxy: no buildable Go source files in D:\mygo\
src\github.com\shell909090\goproxy

D:\mygo>go build
can't load package: package .: no buildable Go source files in D:\mygo

D:\mygo>go build github.com/shell909090/goproxy/goproxy
src\github.com\shell909090\goproxy\sutils\dns.go:6:2: cannot find package "githu
b.com/miekg/dns" in any of:
        C:\Go\src\github.com\miekg\dns (from $GOROOT)
        D:\mygo\src\github.com\miekg\dns (from $GOPATH)
src\github.com\shell909090\goproxy\goproxy\goproxy.go:12:2: cannot find package
"github.com/op/go-logging" in any of:
        C:\Go\src\github.com\op\go-logging (from $GOROOT)
        D:\mygo\src\github.com\op\go-logging (from $GOPATH)

**Comment by xiaokangwang** [comment]
尝试运行 go get github.com/shell909090/goproxy/goproxy

**Comment by yuan78** [comment]
谢谢，可以编译了。
另外请问命令行参数怎么设定，是这个吗？goproxy -config config.json？ port mapping可以不启用吗？如果启用port mapping，命令行又是怎样的？

**Comment by xiaokangwang** [comment]
命令行是一样的，要改的是配置文件

**Comment by yuan78** [comment]
我在linuxmint下编译goproxy, 结果运行时提示"Segmentation fault"，上网查说是可能程序有bug,
指针非空造成的，这个怎么解决？

2015年10月7日星期三，Xiaokang Wang <notifications@github.com> 写道：

**Comment by xiaokangwang** [comment]
我没有遇到过这个问题，尚不清楚如何解决。。抱歉。。。（我路过的，这个程序的源码都没读完一遍呢。。。。）

**Comment by yuan78** [comment]
我在centos7 和ubuntu 14.10都能正常运行，就是linuxmint有问题，真是奇怪。

在 2015年10月8日 上午9:33，Xiaokang Wang <notifications@github.com>写道：

**Comment by xiaokangwang** [comment]
是不是可以通过gdb调试检查出问题的具体原因

**Comment by luckypoem** [comment]
@shell909090  
能提供windows桌面系统和mac系统下的客户端程序吗？

**Comment by shell909090** [comment]
刚从印度回来，前面没有网络，一直没有回复，非常抱歉。同时也谢谢xiaokangwang的解答。

第一个错误很明显，因为缺少依赖。我的建议其实是自己go get这堆依赖的。不过go get主程序包来自行求解依赖也行。

第二个问题我倾向于是你使用的库有问题，因为其他系统下并没有问题。只是我不知道问题在哪里。你能用ulimit打开core dump跑一下，然后给我dump文件么？或者用gdb跑出当时的栈来也行。这样我能定位到是哪里出的问题。

第三个问题，我不建议你直接找编译好的程序，而且我也没有windows和mac的开发环境。使用预编译好的代码有很严重的安全隐患，我强烈的建议你不要相信任何人的二进制发行包，哪怕是我发的。

**Comment by xiaokangwang** [comment]
@luckypoem  Go 1.5 起，通过设置环境变量 GOARCH,GOOS可以进行跨平台编译。但是我也不建议有可能自己编译的人使用别人编译好的程序。

不过你说桌面系统是指有GUI的层序么？
