### ISSUE TITLE
有什么办法改进速度吗？

### ISSUE THREAD

**Issue by luckypoem** [shell909090/goproxy#14]
我在ubuntu桌面系统下，测试成功，可翻墙，不过速度很慢。
（我是在linux桌面系统下,把linux vps上编译好的可执行文件goproxy(即/root/go/bin/goproxy文件）下载到linux桌面系统。然后chmod 755 goproxy,
运行:./goproxy --config config.json）
是因为这是一个http代理，所以速度很慢吗？
作者可否把它改造为socks代理呢？？感觉socks代理好像比http代理快很多

**Comment by shell909090** [comment]
实际上你能感受到的情况下，这和http代理没关系。更多的是你的vps的速度问题。
你可以测试一下vps的速度，着重丢包率。goproxy将多个连接混入一个链路，所以对丢包率很敏感，比ss敏感的多。

**Comment by luckypoem** [comment]
hi,
我在另一个vps也装了goproxy,测试的结果是翻＃墙速度依旧很慢。但是在这台vps上用deblocus/在之前的vps上用shadowsocks翻＃墙都很快。这就只能说明你这个程序设计得有点不够合理。大概就是你说的“对丢包率过于敏感”的问题，可否重新设计一下，使得goproxy对丢包率不那么敏感呢？

**Comment by shell909090** [comment]
要合理很简单啊，改用ss就行了。goproxy的核心设计就是“将多个tcp流封装在一个tcp流里面”，从而破坏流量检测模型。而一旦这么做了，就会造成“对丢包率敏感”。一旦去掉这点，那就是ss的设计。。。
问一下你的丢包率是多少？我的一个vps在24小时内检测1440次丢包率，总计丢包率小于0.5%，高峰期不大于1%。总延迟大约在60ms。极限速度下可以拉到8Mbps。你可以参考一下。

**Comment by shell909090** [comment]
两个很烂的vps的测试结果不能说明程序烂，只能说明vps烂。所以。。。

**Comment by lixingcong** [comment]
"我的一个vps在24小时内检测1440次丢包率"
我手上有3个vps。也想检测一下，怎么进行24小时的丢包监控？

**Comment by shell909090** [comment]
1. ping满24小时。
2. 上smokeping。。。

**Comment by luckypoem** [comment]
hi.
怎么检测丢包率？命令是什么？
“我的一个vps在24小时内检测1440次丢包率”－意思是1分钟才丢一次包。可否说下你用的是哪家的vps吗
谢谢回复。

**Comment by shell909090** [comment]
不。。。一分钟丢一次包就要死人了。。。
丢包率用ping就可以检测，如果要持续检测，可以上一套smokeping。
我用的是buyvm和do singapore的vps。问题不在vps上，在于我用的出国网络是国精网。。。优先级比较高。。。

**Comment by krrr** [comment]
@shell909090 丢包敏感和高速下载时其他连接受影响在ssh隧道或者OpenVPN（复用一个TCP连接时）里也存在吗，vpn会不会用复杂的方法解决了这种问题？

**Comment by shell909090** [comment]
是的，也存在。这也是为什么在做VPN的时候，都要用UDP协议而非TCP协议。。。
实际上TCP协议的VPN情况会更糟。因为TCP在两个层面上都会发起重传，这会使得情况更加糟糕。

**Comment by krrr** [comment]
那么让被代理的连接和代理连接一一对应（ss的做法），但是像http的keep-alive一样当被代理连接关闭后代理连接不关闭，等下一个代理请求到来就重用怎么样呢。好像以前在v2ex看见过，但是ss节点进不去……

**Comment by shell909090** [comment]
你可以试试修改msocks的连接池模型，将极大连接数减少到1，并适当调节连接保持时间，应该能达到你的目标。

**Comment by luckypoem** [comment]
hi.

仔细看了你的readme,并在sysctl.conf的底部添加了：
net.ipv4.tcp_congestion_control = htcp
net.core.rmem_default = 2621440
net.core.rmem_max = 16777216
net.core.wmem_default = 655360
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096        2621440 16777216
net.ipv4.tcp_wmem = 4096        655360  16777216

然后运行sysctl -p遇到权限不够的提示。如何解决？
我的vps是openvz技术，难道是openvz vps的sysctl.conf不支持添加你那些参数？

root@AR:~/go/bin# sysctl -p
net.ipv4.ip_forward = 1
sysctl: permission denied on key 'net.ipv4.tcp_congestion_control'
sysctl: permission denied on key 'net.core.rmem_default'
sysctl: permission denied on key 'net.core.rmem_max'
sysctl: permission denied on key 'net.core.wmem_default'
sysctl: permission denied on key 'net.core.wmem_max'
sysctl: permission denied on key 'net.ipv4.tcp_rmem'
sysctl: permission denied on key 'net.ipv4.tcp_wmem'
root@AR:~/go/bin#

**Comment by kongfei605** [comment]
搜一下。
http://zhidao.baidu.com/question/328155821414120085.html
http://www.111cn.net/sys/CentOS/54693.htm
https://github.com/shadowsocks/shadowsocks/issues/375
期待你的反馈。

2016-07-04 13:38 GMT+08:00 luckypoem <notifications@github.com>:

**Comment by luckypoem** [comment]
@kongfei605 
“要进行修复操作， 修复也很简单，总共四个命令.
修复modprobe：
rm -f /sbin/modprobe 
ln -s /bin/true /sbin/modprobe
修复sysctl：
rm -f /sbin/sysctl 
ln -s /bin/true /sbin/sysctl
按命令来看就是重建这两个模块的软连接.
执行完这四个命令后，你再试试/sbin/sysctl -p，没再报错。”

确实没再报错。

**Comment by luckypoem** [comment]
哈，在kvm vps上重装了你这个goproxy,翻墙速度挺快。在openvz vps上，装的话，翻墙速度就慢多了。看样子，翻墙速度跟vps的虚拟化技术有关。

**Comment by liukangxu** [comment]
两台VPS的网络环境完全一致吗？如果不一致，这样的比较没有任何意义。

**Comment by luckypoem** [comment]
hi.

不过在mac上，半个小时之后，就遇错，如何解决？
yudeMacBook-Air:~ brite$ goproxy --config goproxy-by-shell909090-config.json

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13c6785]

goroutine 21 [running]:
github.com/shell909090/goproxy/msocks.(*SessionPool).getLessSess(0xc420140380, 0xc4201a6928, 0x0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/pool.go:209 +0x95
github.com/shell909090/goproxy/msocks.(*SessionPool).Get(0xc420140380, 0xc420016300, 0x1442820, 0x16f46d0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/pool.go:149 +0x57
github.com/shell909090/goproxy/msocks.(*SessionPool).Dial(0xc420140380, 0x14b506f, 0x3, 0xc4201663e0, 0x11, 0xc42013aff0, 0x1442820, 0x16f46d0, 0x0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/pool.go:243 +0x2f
github.com/shell909090/goproxy/sutils.(Dialer).Dial-fm(0x14b506f, 0x3, 0xc4201663e0, 0x11, 0x0, 0x0, 0xc4201a6a60, 0x12d7d9d)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/goproxy/httproxy.go:33 +0x5b
net/http.(*Transport).dial(0xc420182000, 0x16a3e00, 0xc4200a4600, 0x14b506f, 0x3, 0xc4201663e0, 0x11, 0x0, 0x0, 0x0, ...)
	/Users/brite/go/src/net/http/transport.go:852 +0x7b
net/http.(*Transport).dialConn(0xc420182000, 0x16a3e00, 0xc4200a4600, 0x0, 0xc4201860b4, 0x4, 0xc4201663e0, 0x11, 0x0, 0x0, ...)
	/Users/brite/go/src/net/http/transport.go:1008 +0x1c4c
net/http.(*Transport).getConn.func4(0xc420182000, 0x16a3e00, 0xc4200a4600, 0xc420162c30, 0xc420194120)
	/Users/brite/go/src/net/http/transport.go:908 +0x78
created by net/http.(*Transport).getConn
	/Users/brite/go/src/net/http/transport.go:910 +0x3a3
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13c9d60]

goroutine 37 [running]:
github.com/shell909090/goproxy/msocks.(*Session).Close(0x0, 0x0, 0x0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/session.go:135 +0x70
panic(0x14428e0, 0x16ca360)
	/Users/brite/go/src/runtime/panic.go:489 +0x2cf
github.com/shell909090/goproxy/msocks.(*Session).Run(0x0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/session.go:197 +0x67
github.com/shell909090/goproxy/msocks.(*SessionPool).sessRun(0xc420140380, 0x0)
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/pool.go:236 +0x63
created by github.com/shell909090/goproxy/msocks.(*SessionPool).createSession
	/Users/brite/go/gopath/src/github.com/shell909090/goproxy/msocks/pool.go:200 +0x412
yudeMacBook-Air:~ brite$

**Comment by shell909090** [comment]
@kongfei605 openvz不支持这些参数。

**Comment by shell909090** [comment]
@kongfei605 这个很不好意思，是个程序bug。我建议升级到最新版本再试试，最好是dev和main各试一下。因为去年我重写过一版，稳定性应该有不少提升。
