### ISSUE TITLE
http proxy 的鉴权功能何时会添加？

### ISSUE THREAD

**Issue by wbpmrck** [shell909090/goproxy#15]
RT

**Comment by shell909090** [comment]
goproxy的原本版本有服务器-客户端鉴权。dev分支有http客户端鉴权。你说的是哪个？

**Comment by wbpmrck** [comment]
就是http客户端的鉴权，已经实现了是吗 @shell909090

**Comment by shell909090** [comment]
是的。前一段时间收到了一个朋友的pr。我看了一下，就是这个功能。

**Comment by shell909090** [comment]
https://github.com/shell909090/goproxy/pull/9
