### ISSUE TITLE
看到另一个版本的goproxy，有区别吗

### ISSUE THREAD

**Issue by lixingcong** [shell909090/goproxy#16]
地址 https://github.com/phuslu/goproxy

上面地址是goagent作者的，虽然两个仓库都是goproxy，想知道有什么区别

**Comment by shell909090** [comment]
其实你应该问有啥共同——
——除了名字一樣麼？

**Comment by lixingcong** [comment]
今天试了一下你的goproxy，速度很好。尤其是使用U2B。
不知道为啥，刷推特图片加载略慢，没有shadowsocsk流畅

捣鼓后编译出来了。真是跨平台啊！
服务端是ubuntu 14.04，客户端是Win8.1 x64

感想：比那个phuslu的好用一点。。因为它的vps服务端有时候会无反应。。
毕竟那个phuslu名气太大，现在都不敢在gihub冒泡，也没维护了，跨省追捕啊。

**Comment by shell909090** [comment]
那是因为我把多个tcp流封到一起了。所以如果是一个流在跑，你觉得很流畅。如果是多个流混到一起，并发就不如多个流本身了。
跨平台别看我，那是golang自身的能力。
低调点。

**Comment by lixingcong** [comment]
How to enable ipv6 ?
As for shadowsocks , just easily setting listen all ports on my host and it works perfectly.
What about yours?
Thank you.

**Comment by shell909090** [comment]
that's impossible。When I mix all tcp connectiong in one, I use ipaddr as hard code. So, unless update protocol, goproxy can't support ipv6.
