### ISSUE TITLE
跟TCP_BBR兼容吗？

### ISSUE THREAD

**Issue by fzinfz** [shell909090/goproxy#18]
在 https://github.com/shell909090/goproxy#msocks协议 里看到以下调优tcp配置：
`net.ipv4.tcp_congestion_control = htcp`

是否说明和TCP_BBR（`net.ipv4.tcp_congestion_control=bbr`）不兼容？

**Comment by shellus** [comment]
BBR兼容一切！放心用bbr吧。

**Comment by shell909090** [comment]
放心吧。推荐htcp是因为这个文档出来的时间比bbr早。。。
