### ISSUE TITLE
请问有写入NAS的goproxy方案吗？我看NAS的套件里好像可以安装python

### ISSUE THREAD

**Issue by evilhentaro** [shell909090/goproxy#26]

**Comment by shell909090** [comment]
NAS的套件能安装Python没用啊。NAS的套件能安装golang编译环境么？goproxy是golang写的，不是Python啊。
或者说你能搞出一个NAS的交叉编译环境编译出一个可执行文件么？毕竟我连你NAS的CPU架构都不知道。。。
