### ISSUE TITLE
建议增加kcptun的支持，可以解决数据丢包的问题，加快访问速度

### ISSUE THREAD

**Issue by lchjczw** [shell909090/goproxy#33]
建议增加kcptun的支持，可以解决数据丢包的问题，加快较大的访问速度

**Comment by shell909090** [comment]
非常高兴收到你的反馈。你提议的内容我很早就考虑过，结论是不会这么做。主要是以下几点考虑。

1. KCP基于UDP，而我家这里对于UDP的权重比较低(QoS)。所以，如果换成KCP，除了总体变慢之外没有什么特别好处。全国范围来说，这个情况可能不是一个个例。
2. KCP的网络层比较有特征，这个和goproxy的发展方向正好相反。goproxy的目标是和普通常见协议无差异，从而保证比较大的稳定性，而不是比较高的速度。因此新版协议增加了TLS。舍弃了比较安全的客户端证书验证，建议使用更加常见的服务器端证书验证，客户端用户名密码验证。
3. 从我的观点来看，如果网络质量比较差，应该在系统层解决，或者更换/优化链路，而不是在网络协议上折腾。因为普遍思路都是优化链路。因此网络协议优化就越来越多的出现在某些特定场所，例如手机网络和你懂。这使得协议上无论怎么折腾都很容易被标记，距离2的目标越走越远。

当然，如果你愿意向goproxy中引入kcp支持补丁，我很乐意合并。你只需要实现一个自己的dialer和listener，并且在主程序中根据条件套上去即可。你可能需要注意以下几点。
1. tls层目前没有完全支持chain。目前tls下面只有tcp，所以不构成问题。如果你要引入kcp，请先解决tls的支持问题。
2. 请从dev上继续开发。最后的结果会被引入dev，验证稳定后合并到master。如果你直接在master上开发，将无法保证引入。

最后，再次感激你的提议。

**Comment by lchjczw** [comment]
对于尽量无特征这一点来说，确实是没必要，kcp是在出现丢包严重的时候，速度会更快
