### ISSUE TITLE
尝试使用goreleaser?

### ISSUE THREAD

**Issue by Leviathan1995** [shell909090/goproxy#34]
* 让用户自己编译还是有点麻烦，可以尝试使用goreleaser，每次发版自动编译打包二进制. 效果如下: [releases](https://github.com/Leviathan1995/fari-proxy/releases)
* 关于直连的问题，我没有看代码，我的思路是proxy直连目标IP， 假如成功就直连，否则就尝试Proxy, 并将IP放入Proxy维护的一个blocklist.

**Comment by shell909090** [comment]
逻辑很简单。
首先使用edns-client-subnet查询当前ip应当得到的服务器ip，再用chnroutes判断这个ip是不是在国内。是的话直连，不是的话代理。
编译的问题，我觉得还是让用户自己编译吧。这样对项目不一定好，但是对我好。
