### ISSUE TITLE
能否写个centos的安装使用说明？？

### ISSUE THREAD

**Issue by cfcboy** [shell909090/goproxy#8]
看你写的说明，好像速度更快，稳定性目前还没有使用。。

我用的是CENTOS，但是没有安装WIKI，能不能弄一个呢？

**Comment by shell909090** [comment]
更快速是不可能的。goproxy将多个流混入了一个流内，所以如果不调优tcp，速度应该会更慢而不是更快。
wiki好像不需要安装。
我觉得你需要的不是goproxy的安装文档，而是golang的环境设定文档。对于golang在cent下的环境设定我也不是很清楚，但是在环境设定完成后，将两个依赖的库go get下来，最后go build一下就有了。
依赖的库在.travis.yml里有列。go build的代码在make build里。
